### PR TITLE
[LAN] Block BT Home/Smart Hub

### PR DESCRIPTION
**Pull request by 2secslater**

### CODE REVIEW

**Comment by gwarser** [comment]
I will prefer some links to sources/documentation instead of pull request without description.

Will look into this later.

**Comment by 2secslater** [comment]
Hi,
Sorry for not saying anything last night.

bthomehub.home is what BT Home Hub 4 through 6 use(d). https://www.bt.com/content/dam/bt/help/user-guides/BT-Home-Hub-4-TypeA-user-guide.pdf
BT Home Hub 5 and 6 also used to use it, until BT rebranded Hub 6 as "BT Smart Hub" and it changed to bthub.home. See references to it here - https://shop.bt.com/content/uni2/documentation/90ry/home-hub-5-info-and-troubleshooting.pdf

I am not certain whether the Hub 4 has received a software update changing the domain to bthub.home as I no longer have access to one.

**Comment by gwarser** [comment]
@2secslater how much you care about license? I forget about it when I moved lan-block to uAssets. I will like to put 

    ! Licence: https://github.com/uBlockOrigin/uAssets/blob/master/LICENSE

line in list version in <https://github.com/uBlockOrigin/uAssets/blob/master/filters/lan-block.txt>. Most of the lists maintained in uAssetes are licensed under  GPL3.

**Comment by 2secslater** [comment]
Hi,
I agree it can be relicensed under GPLv3.

**Pull request merged**
